/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package rpgsheet.frames;

import java.awt.event.MouseEvent;
import rpgsheet.elements.Caracteristica;

/**
 *
 * @author Tiago
 */
public class ButtonCaracteristica extends javax.swing.JPanel {

    /**
     * Creates new form ButtonCaracteristica
     */
    private Caracteristica caracteristica;
    public ButtonCaracteristica(final Caracteristica c){
        this();
        caracteristica=c;
        this.label.setText(c.getLabel());
        this.value.setText(c.toString());
        this.label.setToolTipText(c.getDescricao());
    }
    public ButtonCaracteristica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        value = new javax.swing.JButton();
        label = new javax.swing.JLabel();

        value.setText("jButton1");
        value.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        value.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                valueMouseClicked(evt);
            }
        });
        value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valueActionPerformed(evt);
            }
        });

        label.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(value))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(value)
                .addComponent(label))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valueActionPerformed
        // TODO add your handling code here:
        Main.editCaracteristica(caracteristica);            
    }//GEN-LAST:event_valueActionPerformed

    private void valueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_valueMouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == MouseEvent.BUTTON2)
        {
            Main.removeCaracteristica(caracteristica);
        }
    }//GEN-LAST:event_valueMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel label;
    private javax.swing.JButton value;
    // End of variables declaration//GEN-END:variables
}
