package rpgsheet.frames;


import rpgsheet.elements.Ficha;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import rpgsheet.elements.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tiago
 */
public class Janela extends javax.swing.JFrame {
    public Janela() {
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Janela.class.getName()).log(Level.SEVERE, null, ex);
        }//mudar a aparencia da janela
        initComponents();
        Dimension ds = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension dw = getSize();
        setLocation((ds.width - dw.width) / 2, (ds.height - dw.height) / 2);
        getRootPane().setDefaultButton(jButton1);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        left = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        top = new javax.swing.JPanel();
        filePanel = new javax.swing.JPanel();
        newficha = new javax.swing.JButton();
        save = new javax.swing.JButton();
        load = new javax.swing.JButton();
        toolPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        editMode = new javax.swing.JButton();
        mid = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        newInfo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        CharacterInfo = new javax.swing.JTextArea();
        ManageExperience = new javax.swing.JButton();
        ResourcesPanel = new javax.swing.JPanel();
        newResource = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        ResoursesButtonsPanel = new javax.swing.JPanel();
        ItensPanel = new javax.swing.JPanel();
        newItem = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        ItemsText = new javax.swing.JTextArea();
        bottom = new javax.swing.JPanel();
        newAtribute = new javax.swing.JButton();
        newPage = new javax.swing.JButton();
        PaginasTab = new javax.swing.JTabbedPane();
        newHabilidade = new javax.swing.JButton();
        newAdvantage = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 153));
        setMaximumSize(new java.awt.Dimension(567, 759));
        setMinimumSize(new java.awt.Dimension(567, 759));
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.X_AXIS));

        left.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Ficha"));

        top.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        filePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("File"));

        newficha.setText("new");
        buttonGroup1.add(newficha);
        newficha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newfichaActionPerformed(evt);
            }
        });

        save.setText("save");
        save.setBorder(null);
        buttonGroup1.add(save);
        save.setFocusable(false);
        save.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        save.setOpaque(false);
        save.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveMouseClicked(evt);
            }
        });

        load.setText("load");
        load.setBorder(null);
        buttonGroup1.add(load);
        load.setFocusable(false);
        load.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        load.setOpaque(false);
        load.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout filePanelLayout = new javax.swing.GroupLayout(filePanel);
        filePanel.setLayout(filePanelLayout);
        filePanelLayout.setHorizontalGroup(
            filePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filePanelLayout.createSequentialGroup()
                .addComponent(newficha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(save)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(load)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        filePanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {load, newficha, save});

        filePanelLayout.setVerticalGroup(
            filePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(save)
            .addComponent(load)
            .addComponent(newficha)
        );

        filePanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {load, newficha, save});

        toolPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Tools"));

        jButton1.setText("Roll Dice");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        editMode.setText("End edit Mode");
        editMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editModeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout toolPanelLayout = new javax.swing.GroupLayout(toolPanel);
        toolPanel.setLayout(toolPanelLayout);
        toolPanelLayout.setHorizontalGroup(
            toolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolPanelLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editMode)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        toolPanelLayout.setVerticalGroup(
            toolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton1)
                .addComponent(editMode))
        );

        javax.swing.GroupLayout topLayout = new javax.swing.GroupLayout(top);
        top.setLayout(topLayout);
        topLayout.setHorizontalGroup(
            topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(filePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toolPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        topLayout.setVerticalGroup(
            topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(toolPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        filePanel.getAccessibleContext().setAccessibleName("file");

        mid.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        mainPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Character information"));

        newInfo.setText("Edit Info");
        newInfo.setBorder(null);
        newInfo.setOpaque(false);
        newInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newInfoActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        CharacterInfo.setEditable(false);
        CharacterInfo.setColumns(20);
        CharacterInfo.setLineWrap(true);
        CharacterInfo.setRows(5);
        CharacterInfo.setWrapStyleWord(true);
        jScrollPane1.setViewportView(CharacterInfo);

        ManageExperience.setText("Manage Experience");
        ManageExperience.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageExperienceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(newInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ManageExperience))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ManageExperience))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                .addContainerGap())
        );

        ResourcesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Other informations"));

        newResource.setText("new resource");
        newResource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newResourceActionPerformed(evt);
            }
        });

        ResoursesButtonsPanel.setBackground(new java.awt.Color(255, 255, 255));
        ResoursesButtonsPanel.setLayout(new javax.swing.BoxLayout(ResoursesButtonsPanel, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane4.setViewportView(ResoursesButtonsPanel);

        javax.swing.GroupLayout ResourcesPanelLayout = new javax.swing.GroupLayout(ResourcesPanel);
        ResourcesPanel.setLayout(ResourcesPanelLayout);
        ResourcesPanelLayout.setHorizontalGroup(
            ResourcesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResourcesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ResourcesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ResourcesPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(newResource))
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );
        ResourcesPanelLayout.setVerticalGroup(
            ResourcesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResourcesPanelLayout.createSequentialGroup()
                .addComponent(newResource)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4)
                .addContainerGap())
        );

        ItensPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Inventory"));

        newItem.setText("Add item");
        newItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newItemActionPerformed(evt);
            }
        });

        ItemsText.setEditable(false);
        ItemsText.setColumns(20);
        ItemsText.setRows(5);
        jScrollPane3.setViewportView(ItemsText);

        javax.swing.GroupLayout ItensPanelLayout = new javax.swing.GroupLayout(ItensPanel);
        ItensPanel.setLayout(ItensPanelLayout);
        ItensPanelLayout.setHorizontalGroup(
            ItensPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ItensPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ItensPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                    .addGroup(ItensPanelLayout.createSequentialGroup()
                        .addComponent(newItem)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ItensPanelLayout.setVerticalGroup(
            ItensPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ItensPanelLayout.createSequentialGroup()
                .addComponent(newItem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3)
                .addContainerGap())
        );

        javax.swing.GroupLayout midLayout = new javax.swing.GroupLayout(mid);
        mid.setLayout(midLayout);
        midLayout.setHorizontalGroup(
            midLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(midLayout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ResourcesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ItensPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        midLayout.setVerticalGroup(
            midLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ResourcesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ItensPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bottom.setBorder(javax.swing.BorderFactory.createTitledBorder("Paginas"));

        newAtribute.setText("new Atribute");
        newAtribute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newAtributeActionPerformed(evt);
            }
        });

        newPage.setText("new Page");
        newPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPageActionPerformed(evt);
            }
        });

        PaginasTab.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        newHabilidade.setText("new Ability");
        newHabilidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newHabilidadeActionPerformed(evt);
            }
        });

        newAdvantage.setText("new Advantage");
        newAdvantage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newAdvantageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bottomLayout = new javax.swing.GroupLayout(bottom);
        bottom.setLayout(bottomLayout);
        bottomLayout.setHorizontalGroup(
            bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PaginasTab, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(newAtribute, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newAdvantage, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(newHabilidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        bottomLayout.setVerticalGroup(
            bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomLayout.createSequentialGroup()
                .addGroup(bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bottomLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(PaginasTab, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bottomLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(newAtribute)
                        .addGap(18, 18, 18)
                        .addComponent(newHabilidade)
                        .addGap(18, 18, 18)
                        .addComponent(newAdvantage)
                        .addGap(18, 18, 18)
                        .addComponent(newPage)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(bottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(top, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(top, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout leftLayout = new javax.swing.GroupLayout(left);
        left.setLayout(leftLayout);
        leftLayout.setHorizontalGroup(
            leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        leftLayout.setVerticalGroup(
            leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(left);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newItemActionPerformed
        // TODO add your handling code here:
        Main.newItem();
    }//GEN-LAST:event_newItemActionPerformed

    private void newResourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newResourceActionPerformed
        // TODO add your handling code here:
        Main.newResource();
    }//GEN-LAST:event_newResourceActionPerformed

    private void newInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newInfoActionPerformed
        // TODO add your handling code here:
        Main.newInfo();
    }//GEN-LAST:event_newInfoActionPerformed

    private void loadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadActionPerformed
        // TODO add your handling code here:
        Main.load();
        Main.refresh();
    }//GEN-LAST:event_loadActionPerformed

    private void saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseClicked
        // TODO add your handling code here:
        Main.save();
    }//GEN-LAST:event_saveMouseClicked

    private void newfichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newfichaActionPerformed
        // TODO add your handling code here:
        Main.newFicha();
    }//GEN-LAST:event_newfichaActionPerformed

    private void newAtributeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newAtributeActionPerformed
        // TODO add your handling code here:
        Main.newAtribute();
    }//GEN-LAST:event_newAtributeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Main.diceRoll();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void newPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPageActionPerformed
        //NEW PAGE
        Main.newPage();
    }//GEN-LAST:event_newPageActionPerformed

    private void newHabilidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newHabilidadeActionPerformed
        // TODO add your handling code here:
        Main.newHability();
    }//GEN-LAST:event_newHabilidadeActionPerformed

    private void newAdvantageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newAdvantageActionPerformed
        // TODO add your handling code here:
        Main.newAdvantage();
    }//GEN-LAST:event_newAdvantageActionPerformed

    private void editModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editModeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_editModeActionPerformed

    private void ManageExperienceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageExperienceActionPerformed
        // TODO add your handling code here:
        Main.manageExperience();
    }//GEN-LAST:event_ManageExperienceActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea CharacterInfo;
    private javax.swing.JTextArea ItemsText;
    private javax.swing.JPanel ItensPanel;
    private javax.swing.JButton ManageExperience;
    private javax.swing.JTabbedPane PaginasTab;
    private javax.swing.JPanel ResourcesPanel;
    private javax.swing.JPanel ResoursesButtonsPanel;
    private javax.swing.JPanel bottom;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton editMode;
    private javax.swing.JPanel filePanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel left;
    private javax.swing.JButton load;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel mid;
    private javax.swing.JButton newAdvantage;
    private javax.swing.JButton newAtribute;
    private javax.swing.JButton newHabilidade;
    private javax.swing.JButton newInfo;
    private javax.swing.JButton newItem;
    private javax.swing.JButton newPage;
    private javax.swing.JButton newResource;
    private javax.swing.JButton newficha;
    private javax.swing.JButton save;
    private javax.swing.JPanel toolPanel;
    private javax.swing.JPanel top;
    // End of variables declaration//GEN-END:variables
    void refresh() {       
        loadInfo();
        loadResources();
        loadItems();
        loadCaracteristicas();
    }
    private void loadInfo() {
        CharacterInfo.setText(Main.ficha.getExperiencia().toString()+"\n"+Main.ficha.getInfo().toString());
    }
    private void loadResources() {
        ResoursesButtonsPanel.removeAll(); 
        for(Recurso r:Main.ficha.getResources()){
            ResouceClick botao=new ResouceClick(r);            
            ResoursesButtonsPanel.add(botao);
        }
        ResouceClick botao=new ResouceClick(Main.ficha.getLife());            
        ResoursesButtonsPanel.add(botao);
        
    }
    private void loadCaracteristicas() {
        int number;
        number = PaginasTab.getSelectedIndex();
        PaginasTab.removeAll();        
       for(int i=0;i<Main.ficha.getPaginas().size();i++)        
        try{
            Pagina pagina=Main.ficha.getPagina(i);
            PagePanel panel=new PagePanel();
            JPanel lista=panel.getTextPanel();
            PaginasTab.addTab(pagina.getLabel(),panel );
            PaginasTab.setTitleAt(i,Main.ficha.getPaginas().get(i).getLabel());
            lista.removeAll();
            for (int j=0;j<pagina.getSize();j++)
            {
                CaracteristicaClick botao=new CaracteristicaClick(pagina.getElement(j));                
                botao.setToolTipText(pagina.getElement(j).getDescricao());
                lista.add(botao);
            }
        }
        catch(ArrayIndexOutOfBoundsException ex){
            System.out.println("erro de array");
        }
       PaginasTab.setSelectedIndex(number);
    }
    private void loadItems() {
        String text="";
        for(Item r:Main.ficha.getItems()){
           text+=r.toString()+"\n";
        ItemsText.setText(text);
        }
    }

    public int getCurrentPage() {
        return PaginasTab.getSelectedIndex();
    }
}
