/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package rpgsheet.frames;

import javax.swing.JOptionPane;
import rpgsheet.elements.Atributo;

/**
 *
 * @author Tiago
 */
public class WizardMundoDasTrevas extends javax.swing.JFrame {

    int passo=-1;/**
     * Creates new form WizardMundoDasTrevas
     */
    public WizardMundoDasTrevas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        instrucoes = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        instrucoes.setText("clique em info e descreva o personagem");
        jScrollPane1.setViewportView(instrucoes);

        jButton1.setText("proximo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Siga as instrucoes abaixo , depois aperte proximo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 18, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("empty-statement")
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (Main.ficha.getExperiencia().getPontos()==0){
            passo++;
            
            if (passo==0){
                instrucoes.setText("Escolha um entre (fisico,social,mental) e gaste todos os pontos");
                Main.ficha.getExperiencia().increase(7*5);
            } else if (passo==1){
                instrucoes.setText("Escolha um entre (fisico,social,mental) e gaste todos os pontos, nao pode ser o mesmo que no passo anterior");
                Main.ficha.getExperiencia().increase(5*5);
            } else if (passo==2){
                instrucoes.setText("Escolha o que sobrou entre (fisico,social,mental) e gaste todos os pontos");
                Main.ficha.getExperiencia().increase(3*5);
            } else if (passo==3){
                instrucoes.setText("Escolha entre um entre (Talentos,Pericias,Conhecimentos) e gaste todos os pontos,nenhum pode ser maior que 3");
                Main.ficha.getExperiencia().increase(13*2);
            } else if (passo==4){
                instrucoes.setText("Escolha entre um entre (Talentos,Pericias,Conhecimentos) e gaste todos os pontos,nenhum pode ser maior que 3 e nao pode ser o mesmo que no passo anterior");
                Main.ficha.getExperiencia().increase(9*2);
            } else if (passo==5){
                instrucoes.setText("Escolha o que sobrou entre (Talentos,Pericias,Conhecimentos) e gaste todos os pontos,nenhum pode ser maior que 3");
                Main.ficha.getExperiencia().increase(5*2);
            } else if (passo==6){
                instrucoes.setText("Gaste os todos os pontos em Disciplinas, cheque as Disciplinas do seu cla no manual");
                Main.ficha.getExperiencia().increase(3*7);
            } else if (passo==7){
                instrucoes.setText("Gaste todos os pontos em Virtudes");
                Main.ficha.getExperiencia().increase(7*2);
            } else if (passo==8){
                instrucoes.setText("Gaste todos os pontos em Antecedentes");
                Main.ficha.getExperiencia().increase(5*1);
            } else if (passo==9){
                try {
                Main.ficha.findRecurso("Humanidade").setValor(    ((Atributo)(Main.ficha.findAtributo("Conciencia"))).getValor()
                                                                + ((Atributo)(Main.ficha.findAtributo("Auto-Controle"))).getValor());
                Main.ficha.findRecurso("Forca de Vontade").setValor( ((Atributo)(Main.ficha.findAtributo("Coragem"))).getValor());
                } catch (NullPointerException ex) {System.out.println("atributos faltando");};
                instrucoes.setText("Gaste o restante dos pontos como quiser e clique proximo para terminar");
                Main.ficha.getExperiencia().increase(15);
            } else dispose();            
            Main.refresh();
            
        }
        else JOptionPane.showMessageDialog(rootPane,"Voce tem pontos restantes");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WizardMundoDasTrevas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WizardMundoDasTrevas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WizardMundoDasTrevas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WizardMundoDasTrevas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WizardMundoDasTrevas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane instrucoes;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
